### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by dheeru999** [weinman/cnn_lstm_ctc_ocr#10]
while i am running the file train.py,i am facing the following issue. please can any one suggest me?

![screenshot from 2017-11-16 17-24-37](https://user-images.githubusercontent.com/31062594/32890072-4beb4734-caf3-11e7-9427-e031de414a26.png)

**Comment by weinman** [comment]
Does this happen with the standard script in the README? That is, if you do a fresh git clone and run

    make mjsynth-download
    make mjsynth-tfrecord
    make train

or perhaps just

    make train

Is this the result?

I recently pushed a change to the convolution and sequence length calculation. There's a small possibility that oversight was related to this. Try also pulling the latest master branch (e85d6dccac6e92492b8445b7c9e43ebe474bfe76).
