### ISSUE TITLE
Train on more characters?

### ISSUE THREAD

**Issue by hiepph** [weinman/cnn_lstm_ctc_ocr#17]
I want to recognize more than just English alphabet and numbers (e.g. special Unicode characters). Is this possible and how can I do this?

Suppose I have my own dataset, do I have to write my own data loader and provide 

```
out_charset="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
```

like in your `src/mjsynth.py`

**Comment by weinman** [comment]
The model itself doesn't use any particular alphabet. You simply need a way to map the labels to a set of consecutive positive integers (that's how the ctc layer works in tensorflow).

As you noted, I do this in `src/mjsynth.py` by constructing a single string and then using the characters' indices. For other unicode characters, you'd want to make sure the use of `string.index` as in the [data generator](https://github.com/weinman/cnn_lstm_ctc_ocr/blob/cf64a7fba57479f001865193cc980577dc7e6d1c/src/mjsynth-tfrecord.py#L143) works for them.
