### ISSUE TITLE
Empty output in validate.py

### ISSUE THREAD

**Issue by hiepph** [weinman/cnn_lstm_ctc_ocr#18]
For prediction of  some real images, I ran your script:

```
cd src ; python validate.py < ~/paths_to_images.txt
```

and received empty output (it didn't print anything into screen).
I went to check your code and found this line:

```
[output] = sess.run(prediction,{ image: image_data, width: image_data.shape[1]} )
```

and tried to `print(output)`:

```
SparseTensorValue(indices=array([], shape=(0, 2), dtype=int64), values=array([], dtype=int64), dense_shape=array([1, 0]))
```

As expected its values is an empty array `[]`.

What went wrong?

**Comment by weinman** [comment]
Your model might be only predicting blanks.
