### ISSUE TITLE
About the checkpoint

### ISSUE THREAD

**Issue by Fangction** [weinman/cnn_lstm_ctc_ocr#23]
Hello, sir. I am s student just start the learning about tensorflow. I met a few problems when running this program. Can you upload the checkpoint. Thank you!

**Comment by weinman** [comment]
What version of tensorflow are you using? The master branch has only been tested up to Tensorflow 1.2. While an update for Tensorflow 1.8 is in progress, it's not functional yet.

**Comment by Fangction** [comment]
Very Sorry for my late reply! Busy with my homework. I use Tensorflow 1.2

**Comment by weinman** [comment]
@Fangction, in order for the community to provide any help, you need to provide more detail about your problem, i.e. the command sequence issued, stack trace, and execution environment. 

The code is provided to share knowledge with the community. I myself cannot promise to solve the issue, but if it is definitely a problem with the software, I may try.
