### ISSUE TITLE
Memory soon used up when running train step

### ISSUE THREAD

**Issue by xray1111** [weinman/cnn_lstm_ctc_ocr#24]
After running 'make mjsynth-download' and 'make mjsynth-tfrecord', I went to the 3rd step to train the model by running 'make train', but the machine's memory(32G) was soon used up in 2 secends and the host hang and restarted. What's the possible cause of this issue?

**Comment by weinman** [comment]
I'm not entirely sure; I've never had memory issues except when I set the batch size too large. I've only tested on GPUs with 12GB or less, but never had a problem with the default parameters. You might need to do some diagnostics to determine where in the pipeline the memory bloat is happening. (I'm not entirely sure how to do that in tensorflow.)

Also, the master branch is only tested through TF 1.2, though I am working to update for the latest TF.

**Comment by weinman** [comment]
@xray1111  if 32G is your HOST memory (not GPU), that's not enough for the default parameters (my system loads up a python process using 0.548t of total virtual memory and 3.396g of resident memory). You could try using a smaller batch size and number of input readers.

I'm not sure it would help, but I've updated master to use tensorflow 1.8, so you could try that.
