### ISSUE TITLE
How can I make own words-000.tfrecord ?

### ISSUE THREAD

**Issue by hskzlj** [weinman/cnn_lstm_ctc_ocr#29]
When debugging, I find the type is tensor of image,width...
==========================================================
image = tf.image.decode_jpeg( features['image/encoded'], channels=1 ) #gray
    width = tf.cast( features['image/width'], tf.int32) # for ctc_loss
    label = tf.serialize_sparse( features['image/labels'] ) # for batching
    length = features['text/length']
    text = features['text/string']
    filename = features['image/filename']
==========================================================

Could you please tell me how to create my own words-000.tfrecord ?

Thank you!

**Comment by weinman** [comment]
I don't understand your question/problem. If you are running the code as provided and one of the example commands, please provide those details, along with your execution envrionment and a stack trace. 

If you have a question about how to do things generally in tensorflow (i.e., storing TFRecords to disk), you should try asking on stackoverflow.

**Comment by hskzlj** [comment]
Thank you for your answer!

I have not described it in detail. Now I have debug the code and found the
field of the image such as image/text_string, image/height ...

So I can make my own tfrecord with my image.
