### ISSUE TITLE
State-of-the-art

### ISSUE THREAD

**Issue by skalinin** [weinman/cnn_lstm_ctc_ocr#3]
Hi! Thanks for your work!
Do you know which algorithm is now state-of the-art in OCR since crnn was invented two years ago? Are there some new models that are based (may be) on the crnn (convolutional and recurrent)?

**Comment by novioleo** [comment]
@skalinin you can read the paper of Xiang Bai who is the prof. of HUST MCLab.
they did much work in word recognition~
I read some paper recently,and noticed that the accuracy not improved obviously.and some paper can't work like paper described~

**Comment by skalinin** [comment]
Thanks a lot!

**Comment by novioleo** [comment]
my pleasure

**Comment by weinman** [comment]
Stay tuned in November for the results of the ICDAR 2017 Robust Reading Competitions: http://rrc.cvc.uab.es

Currently, the 2015 Challenge 2.2 (word recognition) and 2.4 (end-to-end) leader boards include an attention-based CNN+RNN, as well as a CNN+RNN+CTC.
