### ISSUE TITLE
lexicon.txt'function?

### ISSUE THREAD

**Issue by gydlcc** [weinman/cnn_lstm_ctc_ocr#30]
@weinman  why we use lexicon.txt? what is lexicon.txt's function? what does that for？

**Comment by weinman** [comment]
The option to use a lexicon was introduced for a [customized lexicon-based beam-search decoder.](https://github.com/murphymatt/tensorflow/blob/master/README.md) This work is still ongoing and will be better documented here once the integration is finalized.

**Comment by gydlcc** [comment]
oh oh , thank you pretty much for your answer!

**Comment by gydlcc** [comment]
@weinman  eh if my dataset is gray level image which means the color channel is 1 rather than 3, is still this   program work? or should i change somewhere?

**Comment by weinman** [comment]
This is a separate question of no relation to a lexicon. 

Nevertheless, [yes](https://github.com/weinman/cnn_lstm_ctc_ocr/blob/master/src/model.py#L80), the model works on grayscale, though changing it for color is trivial.

**Comment by gydlcc** [comment]
yeah, thank you very much
