### ISSUE TITLE
Which fork tensorflow are you using?

### ISSUE THREAD

**Issue by QingqingWang-1** [weinman/cnn_lstm_ctc_ocr#34]
I tried to find the fork tensorflow that contains "tf.nn.ctc_beam_search_decoder_trie", However, I cannot find it. Could you tell me which one are you using?

**Comment by weinman** [comment]
Thanks for your interest. It's not quite ready for a "publicized" release on this repo, as there are still bugs. However, if you want to link with it, you can merge the the master branch of [this fork](http://github.com/murphymatt/tensorflow) into your latest TF.

**Comment by QingqingWang-1** [comment]
Many thanks, weinman. I will try it.
