### ISSUE TITLE
python validate.py problem

### ISSUE THREAD

**Issue by gydlcc** [weinman/cnn_lstm_ctc_ocr#35]
hi there!
when i  type python validate.py and i type 1.jpg
i got follow error 

![2018-08-02 15-42-18](https://user-images.githubusercontent.com/26570842/43569888-7cb6f982-966b-11e8-98e3-427904c6faab.png)
 
how could i solve this, 
thanks

**Comment by weinman** [comment]
The validate script is tied to the MJsynth data, which is only 31 pixels high. Thus the raw data's placeholder is (31,?,1) and the tensor gets expanded to 32 pixels high in the `_preprocess_image` function. 

If you delete line 65

    image = tf.concat([first_row, image], 0)

and change line 74 in `_get_input to` to create a 32-pixel high value instead, 

    image = tf.placeholder(tf.uint8, shape=[32, None, 1])

it should work for your data, which seems to be 32 pixels high already.

**Comment by gydlcc** [comment]
oh oh thanks pretty much !  ! 
so if i use the data trained the model, and if i use another data which has different size from the train data to validate the trained model, is that possible?

**Comment by weinman** [comment]
The width is variable, but the height is ostensibly fixed, unless perhaps you introduce a new pooling operation. See #33 for more.
