### ISSUE TITLE
Saving Checkpoint

### ISSUE THREAD

**Issue by sahilbandar** [weinman/cnn_lstm_ctc_ocr#36]
Hi @weinman sir, 
I've run the training for this model. In the source file, I've noticed that model is not saving the checkpoint on basis of less loss, and I am not able to get what is accuracy of the model till now. I want to know that, on which basis it is saving the checkpoints. 
Thank You...

**Comment by weinman** [comment]
[time elapsed](https://github.com/weinman/cnn_lstm_ctc_ocr/blob/7e68b64ed6b54a7da7b7c4dd2db80e0de684e3d4/src/train.py#L201)
