### ISSUE TITLE
Hi Can I use this code for English word recognition in an image for different fonts and different font sizes. Can you plz help me. Thanks

### ISSUE THREAD

**Issue by SANDAFERNANDO** [weinman/cnn_lstm_ctc_ocr#39]

**Comment by Sierkinhane** [comment]
You can refer to
https://github.com/Sierkinhane/crnn_chinese_characters_rec
Maybe it will help you

**Comment by sahilbandar** [comment]
Yeah! You can use this for any font style size and shape for englist alphanumeric, but input matrix must be 31x?

**Comment by weinman** [comment]
Yes, but see [#35](https://github.com/weinman/cnn_lstm_ctc_ocr/issues/35#issuecomment-410245323) and #33 for more background.
