### ISSUE TITLE
Loading the model only once.

### ISSUE THREAD

**Issue by sahilbandar** [weinman/cnn_lstm_ctc_ocr#41]
I want to load the model only once and pass the N number of images for recognition, but whenever I'm passing images, model is loading again and again. I tried to load model in another function and using the same session variable for future recognition but it is giving error `raise RuntimeError('Attempted to use a closed Session.')
RuntimeError: Attempted to use a closed Session.`

**Comment by weinman** [comment]
Which script are you trying to use? It sounds like `validate.py` has the use case you're after.

**Comment by sahilbandar** [comment]
I've modified the script for passing the image to method recognise_text() from another file by creating the object of class Recogniser. Please Reffer the code given below.
It is same as a validate.py just I've converted it to the Object Oriented.
`
# CNN-LSTM-CTC-OCR
# Copyright (C) 2017, 2018 Jerod Weinman
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
import sys
import functools

import numpy as np

from PIL import Image

import tensorflow as tf
from tensorflow.contrib import learn

from src import mjsynth
from src import model
from src.lexicon import dictionary_from_file


class Recogniser:
    FLAGS = tf.app.flags.FLAGS

    tf.app.flags.DEFINE_string('model', '/home/sushant/sahil/cnn_lstm_ctc_ocr/data/model_copy_one',
                            """Directory for model checkpoints""")
    tf.app.flags.DEFINE_string('device', '/gpu:0',
                            """Device for graph placement""")
    tf.app.flags.DEFINE_string('lexicon', '',
                            """File containing lexicon of image words""")

    tf.logging.set_verbosity(tf.logging.WARN)
    
    os.environ['CUDA_VISIBLE_DEVICES'] = '0'
    # Non-configurable parameters
    mode = learn.ModeKeys.INFER  # 'Configure' training mode for dropout layers

    def _get_image(self, img):
        """Load image data for placement in graph"""
        image = np.array(img)
        # in mjsynth, all three channels are the same in these grayscale-cum-RGB data
        # so just extract first channel, preserving 3D shape
        image = image[:, :, :1]

        return image


    def _preprocess_image(self, image):

        # Copied from mjsynth.py. Should be abstracted to a more general module.

        # Rescale from uint8([0,255]) to float([-0.5,0.5])
        image = tf.image.convert_image_dtype(image, tf.float32)
        image = tf.subtract(image, 0.5)

        # Pad with copy of first row to expand to 32 pixels height
        first_row = tf.slice(image, [0, 0, 0], [1, -1, -1])
        image = tf.concat([first_row, image], 0)

        return image


    def _get_input(self):
        """Set up and return image and width placeholder tensors"""

        # Raw image as placeholder to be fed one-by-one by dictionary
        image = tf.placeholder(tf.uint8, shape=[31, None, 1])
        width = tf.placeholder(tf.int32, shape=[])  # for ctc_loss

        return image, width


    def _get_output(self, rnn_logits, sequence_length):
        """Create ops for validation
        predictions: Results of CTC beacm search decoding
        """
        with tf.name_scope("test"):    
            if (self.FLAGS.lexicon):
                dict_tensor = _get_dictionary_tensor(self.FLAGS.lexicon, mjsynth.out_charset)
                predictions, _ = tf.nn.ctc_beam_search_decoder_trie(rnn_logits,
                                                                sequence_length,
                                                                alphabet_size=mjsynth.num_classes(),
                                                                dictionary=dict_tensor,
                                                                beam_width=128,
                                                                top_paths=1,
                                                                merge_repeated=True)
            else:
                predictions, _ = tf.nn.ctc_beam_search_decoder(rnn_logits,
                                                            sequence_length,
                                                            beam_width=128,
                                                            top_paths=1,
                                                            merge_repeated=True)
        return predictions


    def _get_session_config(self):
        gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.333)
        """Setup session config to soften device placement"""
        config = tf.ConfigProto(
            allow_soft_placement=True,
            log_device_placement=False, gpu_options=gpu_options)

        return config


    def _get_checkpoint(self):
        """Get the checkpoint path from the given model output directory"""
        ckpt = tf.train.get_checkpoint_state(self.FLAGS.model)

        if ckpt and ckpt.model_checkpoint_path:
            ckpt_path = ckpt.model_checkpoint_path
        else:
            raise RuntimeError('No checkpoint file found')

        return ckpt_path


    def _get_init_trained(self):
        """Return init function to restore trained model from a given checkpoint"""
        saver_reader = tf.train.Saver(
            tf.get_collection(tf.GraphKeys.GLOBAL_STEP) +
            tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES)
        )

        def init_fn(sess, ckpt_path): return saver_reader.restore(sess, ckpt_path)
        return init_fn


    def _get_string(self, labels):
        """Transform an 1D array of labels into the corresponding character string"""
        string = ''.join([mjsynth.out_charset[c] for c in labels])
        # print string
        return string


    def _get_dictionary_tensor(self, dictionary_path, charset):
        return tf.sparse_tensor_to_dense(tf.to_int32(
        dictionary_from_file(dictionary_path, charset)))

    def recognise_text(self, img):
        print(img.shape)
        with tf.Graph().as_default():
            image, width = self._get_input()  # Placeholder tensors

            proc_image = self._preprocess_image(image)
            # Make first dim batch
            proc_image = tf.reshape(proc_image, [1, 32, -1, 1])

            with tf.device(self.FLAGS.device):
                features, sequence_length = model.convnet_layers(proc_image, width,
                                                                self.mode)
                logits = model.rnn_layers(features, sequence_length,
                                        mjsynth.num_classes())
                prediction = self._get_output(logits, sequence_length)

            session_config = self._get_session_config()
            restore_model = self._get_init_trained()

            init_op = tf.group(tf.global_variables_initializer(),
                            tf.local_variables_initializer())

            with tf.Session(config=session_config) as sess:

                sess.run(init_op)
                restore_model(sess, self._get_checkpoint())  # Get latest checkpoint
                # Iterate over filenames given on lines of standard input
                image_data = self._get_image(img)
                # Get prediction for single image (isa SparseTensorValue)
                [output] = sess.run(prediction, {image: image_data,
                                                 width: image_data.shape[1]})
                #print output
                return self._get_string(output.values)


`

**Comment by weinman** [comment]
Right. You'll need to construct the graph, initialize the session, and process your images in separate functions so that the first two steps happen only once. Please post other Tensorflow questions to StackOverflow.
