### ISSUE TITLE
ctc_beam_search_decoder_trie Tensorflow Operator not found

### ISSUE THREAD

**Issue by thomasdhc** [weinman/cnn_lstm_ctc_ocr#43]
I was unable to find a Tensorflow operator called ctc_beam_search_decoder_trie. Was this a custom Tensorflow operator you created?

Thanks!

**Comment by weinman** [comment]
Yes, it's custom. See #34 The implementer didn't finish it and it doesn't work correctly, so I recommend you look at [CTCWordBeamSearch](https://github.com/githubharald/CTCWordBeamSearch)

**Comment by thomasdhc** [comment]
Thank you!
