### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by hounaidaMoallaF** [weinman/cnn_lstm_ctc_ocr#45]
Please, can you give me you pre-trained model for test

**Comment by weinman** [comment]
See #40.

I train using a platform with multiple GPUS, and the graph in the training checkpoints reflects this; they are not suitable for general use. Hence, if someone wrote script that harnesses only the model parameters necessary for test, I would gladly use it to package a test model. I don't have time nor need for such a script myself.

**Comment by weinman** [comment]
The model checkpoint (trained using MapTextSynth) from the ICDAR 2019 paper is posted here: https://weinman.cs.grinnell.edu/data/cnn_lstm_ctc_ocr_checkpoint_icdar19.tar.bz2
