### ISSUE TITLE
passing the session .

### ISSUE THREAD

**Issue by imohamadhoseins** [weinman/cnn_lstm_ctc_ocr#46]
hey , thank you for your nice code ! 
I want to load the model just once and pass the session for several predicts .
because of loading the model time .
I just wonder how to do it , please help ! , thanks .

**Comment by weinman** [comment]
Thanks. The [validate.py](https://github.com/weinman/cnn_lstm_ctc_ocr/blob/master/src/validate.py) program gives a simple example of this use case under the current code. 

The [old version](https://github.com/weinman/cnn_lstm_ctc_ocr/blob/tf-1.8/src/validate.py) didn't have the nice `Estimator`/`Dataset` abstractions, so you may perhaps find it more directly useful.
