### ISSUE TITLE
Using Multiple GPU as a train_device

### ISSUE THREAD

**Issue by sahilbandar** [weinman/cnn_lstm_ctc_ocr#51]
I need just small help in training the model in multiple GPU so as option is availble --train_device I'm able to mention only one device. How I can mention the both of gpu as train device.

**Comment by weinman** [comment]
What revision are you using? The `--train_device` option was removed with the latest version in favor of `--num_gpus`. 

NB: You can't fine tune if you start a model with multiple GPUs, because the `tf.train.Scaffold` [doesn't work](https://github.com/tensorflow/tensorflow/issues/21615)

**Comment by sahilbandar** [comment]
yes, I am using the old source.

**Comment by weinman** [comment]
You should pull the latest master (or tag tf-1.10) to get multi-GPU training functionality. The previous version doesn't support it, even if you make multiple GPUs visible to CUDA, I don't believe the training will be distributed across them. We now utilize `tf.distribute.MirroredStrategy` for that.
