### ISSUE TITLE
are there any pretrain model file

### ISSUE THREAD

**Issue by syedmustafa54** [weinman/cnn_lstm_ctc_ocr#53]
@weinman
**1.** Is there any pre-train model file so i can just check it 
**2.** When I ran make command  its creating tfrecords files and terminal output is below its skipping some files may be for test use I think
here is the terminal output 
`177 of 1000 [ 1278825 : 1286050 ] ../data/train/words-177.tfrecord
('SKIPPING', '1993/4/472_nj_51777.jpg')
('SKIPPING', '1991/5/238_d_18979.jpg')
('SKIPPING', '1991/5/204_V_83811.jpg')
('SKIPPING', '1991/4/228_j_41074.jpg')
178 of 1000 [ 1286050 : 1293275 ] ../data/train/words-178.tfrecord
('SKIPPING', '1990/1/447_4_95.jpg')
('SKIPPING', '1989/4/34_NI_51538.jpg')
('SKIPPING', '1988/3/445_CORRECTNESS_17153.jpg')
179 of 1000 [ 1293275 : 1300500 ] ../data/train/words-179.tfrecord
('SKIPPING', '1987/7/56_n_50734.jpg')
('SKIPPING', '1987/6/477_SJ_71221.jpg')
('SKIPPING', '1987/6/102_RADIOTELEPHONE_62145.jpg')
('SKIPPING', '1986/1/175_INDIVIDUALISTICALLY_39086.jpg')
180 of 1000 [ 1300500 : 1307725 ] ../data/train/words-180.tfrecord
('SKIPPING', '1985/1/50_Debaucheries_19549.jpg')
181 of 1000 [ 1307725 : 1314950 ] ../data/train/words-1`

**Comment by weinman** [comment]
1. See #40 and #45 
2. See #28 (specifically [this](https://github.com/weinman/cnn_lstm_ctc_ocr/issues/28#issuecomment-397603749)).

**Comment by syedmustafa54** [comment]
Thanks For the reply I should have checked the issues than ask :+1:

**Comment by weinman** [comment]
The model checkpoint (trained using MapTextSynth) from the ICDAR 2019 paper is posted here: https://weinman.cs.grinnell.edu/data/cnn_lstm_ctc_ocr_checkpoint_icdar19.tar.bz2
