### ISSUE TITLE
Input shapes: [72,357,1], [4] and with input tensors computed 

### ISSUE THREAD

**Issue by syedmustafa54** [weinman/cnn_lstm_ctc_ocr#54]
@weinman Hello,
**1.** I have seen this [#35](https://github.com/weinman/cnn_lstm_ctc_ocr/issues/35#issuecomment-409908477) But the which file name  its not given even i checked `validate.py,` `mjsynth.py`, `model_fn.py` but was not able to find this line
`image = tf.concat([first_row, image], 0)
`
or this
`image = tf.placeholder(tf.uint8, shape=[32, None, 1])`

```
tensorflow/python/framework/ops.py", line 1631, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension size must be evenly divisible by 32 but is 25704 for 'Reshape' (op: 'Reshape') with input shapes: [72,357,1], [4] and with input tensors computed as partial shapes: input[1] = [1,32,?,1].

```
**2.** In the default train data are there any Number Present I mean 123. I have checked it but its not availble. If i want to train my coustom data how is the labling done i usally use bonding box but this is different can you tell me how is the lableing done and how to train coustom data. Forgive me for my english is not good.

**Comment by weinman** [comment]
1. Judging from the error, you're not using an image that's exactly 32 pixels high, which is a pre-requisite for the model. (Except that `mjsynth.preprocess_image()` adds an extra row because that data is mysteriously all 31 pixels high.)
2. I believe some are, but I'm not sure; you can check in the lexicon.txt file that gets downloaded with the archive.

**Comment by syedmustafa54** [comment]
So can we not use the image higher than 32 pixels or do you have any function which do auto resize it to 32 if not than i will write my own resizer and send to server

**Comment by weinman** [comment]
If the images are for training (i.e., they're going into tfrecord files), you should resize them beforehand, so the training pipeline is more efficient. If you're just quickly validating some existing files by giving the paths to `validate.py`, you could perhaps alter the pipeline by exchanging `mjsynth.preprocess_image` for `pipeline.normalize_image` (or a similar function of your own creation) in [_get_input()](https://github.com/weinman/cnn_lstm_ctc_ocr/blob/defd8aeef5b408d409bcf3ce6a64723b02b3676f/src/validate.py#L71).
