### ISSUE TITLE
It's possible to use a pre-trained model?

### ISSUE THREAD

**Issue by ambigus9** [weinman/cnn_lstm_ctc_ocr#55]
Hi, it is possible to train a model using my own data and also at the same time a pre-trained model? Thanks.

**Comment by weinman** [comment]
You can use the `--tune_from` flag of `train.py` to load a previous model training checkpoint with a different `--train_path` and/or `--filename_pattern` with which to continue training. Anything beyond that will likely require you to modify the code.
