### ISSUE TITLE
FineTune !

### ISSUE THREAD

**Issue by imohamadhoseins** [weinman/cnn_lstm_ctc_ocr#58]
hey thanks for your codes again :)
the question is that is it posiible to finetune the trained model fom your networks with your codes ?

**Comment by weinman** [comment]
If you're asking whether I have pretrained models, the answer is no (See #40 and #45). If the question is how do you train only some of the weights, then you train using the `--tune_from` flag to indicate the initial model weights and `--tune_scope` to restrict the categories of weights that you want to adjust. For example, all the LSTM weights have the variable scope "rnn" (e.g., see [this line](https://github.com/weinman/cnn_lstm_ctc_ocr/blob/defd8aeef5b408d409bcf3ce6a64723b02b3676f/src/model.py#L183) in `model.py`.

**Comment by imohamadhoseins** [comment]
how to use the flag in command ? can you make an example ?

**Comment by weinman** [comment]
@imohamadhoseins See the newfangled FAQ.
