### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by w867066886** [weinman/cnn_lstm_ctc_ocr#60]
There is a error " __init__() got an unexpected keyword argument 'train_distribute'" 
I search the function   'tf.estimator.RunConfig' and don't find the parameter "train_distribute" 
Coule you help me  correct it?
i use python2.7 and tensorflow1.5

**Comment by weinman** [comment]
This package requires a newer version of tensorflow. It's currently set to use tf≥1.10

**Comment by w867066886** [comment]
Thansk for your answer , it is running now .

It takes a lot of the memory of gpu , but a low use of gpu-util.
Im using  four gtx1080ti ,but when i enter the "make test" ,it tell me " OOM when allocating tensor with shape[512,64,31,125] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc" 

Should I stop trainning and to test?
Look forward to your reply， thanks
![image](https://user-images.githubusercontent.com/28303150/56478115-36b7a380-64df-11e9-8d78-ed33cffc2920.png)

**Comment by weinman** [comment]
I've used the same device with no memory troubles in test. Odd.

You can reduce the batch size or run test on the CPU, since most of the computation (in test) happens there anyway. [That's why you'll have low GPU utilization.]

**Comment by weinman** [comment]
I think I (belatedly) understand now that perhaps you're running the test while you're also doing training? If your trainer has claimed all of the GPUs, the tester won't have room to allocate memory, because tensorflow (by default) tries to allocate all the available memory.
