### ISSUE TITLE
Fixed sequence length

### ISSUE THREAD

**Issue by SnehalRaj** [weinman/cnn_lstm_ctc_ocr#61]
I am working with a real life dataset where I am getting quite good results with your code. However,  most of the errors, I believe are due to an incorrect prediction of sequence length. My dataset has words which are of fixed length(and format too).
 Is there any way where I could modify the code so it would predict sequences, of the length (and in the format) I specify it?

**Comment by weinman** [comment]
Connectionist Temporal Classification (CTC) is targeted for aligning input and output label sequences, particularly where the length is variable. To address your use case, you'll likely need to change the loss function for a different encoding/merging scheme and the decoder to output fixed sequence lengths.
