### ISSUE TITLE
Training Error when using my data 

### ISSUE THREAD

**Issue by hxk11111** [weinman/cnn_lstm_ctc_ocr#62]
After writing my own data to tfrecord using mjsynth-tfrecord.py. I tried to train the model using train.py. But I got the error below, could anyone help me to solve this problem. Many thanks.
![MacHi 2019-07-16 15-47-15](https://user-images.githubusercontent.com/23485433/61275693-11d28400-a7e1-11e9-9530-eb7c213343d5.png)

**Comment by weinman** [comment]
Please don't post images to issues; they are not searchable. (Especially if you can't get your OCR to work. :-P)

Then, see #33, #35, #39. (Aka, follow github's instructions to search related issues first.)
