### ISSUE TITLE
0% GPU-Util when testing

### ISSUE THREAD

**Issue by hxk11111** [weinman/cnn_lstm_ctc_ocr#63]
Hi weinman, Thanks for sharing your project.
I have some questions, hope someone could help

- When testing use my own data, the gpu memory usage is normal, but the gpu-util is 0%, and the testing process is very slow. Does anyone have similar problem?

- I saw your project has a predicting by lexicon part, do I need to modify validate.py and test.py if I use this part?

-  Since training, validation, testing parts are seperated in this project, is there a way I can train and validate in the same time?

**Comment by weinman** [comment]
1. Yes, see  #31. Change the beam width or to greedy search (but that gives poorer performance).

I'll gladly answer 2. and 3., but could you please kindly move them to new, separate issues to keep the subsequent threads clearer?
